

puns = """
How much money does a pirate pay for corn? A buccaneer.:Don't interrupt someone working intently on a puzzle. Chances are, you'll hear some crosswords.:I'm a big fan of whiteboards. I find them quite re-markable.:The machine at the coin factory just suddenly stopped working, with no explanation. It doesn't make any cents!:I was going to make myself a belt made out of watches, but then I realized it would be a waist of time.:Did you hear about the auto body shop that just opened? It comes highly wreck-a-mended.:What sound does a sleeping T-Rex make? A dino-snore.:Two windmills are standing in a wind farm. One asks, "What's your favorite kind of music?" The other says, "I'm a big metal fan.":Want to hear something terrible? Paper. See? I told you it was tear-able.:Last night, I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta sea.:Atoms are untrustworthy little critters. They make up everything!:The past, the present, and the future walk into a bar… It was tense.:Someone stole my toilet and the police have nothing to go on.:Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.:What do you call a thieving alligator? A Crookodile.:What do you call a pig that does karate? Pork chop.:Why did the banana go to the doctor? It wasn't peeling well.:How does a squid go into battle? Well-armed.:Why aren't koalas actual bears? They don't meet the koalafications.:I was wondering why the ball was getting bigger. Then it hit me.:Did you hear about the guy whose whole left side was cut off? He’s all right now.

"""

videos = ['https://www.youtube.com/watch?v=iik25wqIuFo','https://www.youtube.com/watch?v=QTT5iHCHSn0','https://www.youtube.com/watch?v=G7RgN9ijwE4&list=PLysK5kM8r78sJFo--opGDHCdTgNJTIb-o','https://www.youtube.com/watch?v=a8c5wmeOL9o&list=PLA-NG0Qt9Jm4SESHbFgfCdNQnF7IMVHbD','https://www.youtube.com/watch?v=puGA2N5pxeI&list=PL_90hJucBAcPmFxcbTea81OKGkQevH2F9&index=23','https://www.youtube.com/watch?v=puGA2N5pxeI&list=PL_90hJucBAcPmFxcbTea81OKGkQevH2F9&index=23','https://www.youtube.com/watch?v=U9M7De-90JQ&list=PLDAt_4uwQO2LJnZZ7ZKQpEZBqWxYVZu_x','https://www.youtube.com/watch?v=ggJueBSS_P0&list=PLDAt_4uwQO2LJnZZ7ZKQpEZBqWxYVZu_x&index=5','https://www.youtube.com/watch?v=BhEfvGZM6jw&list=PLDAt_4uwQO2LJnZZ7ZKQpEZBqWxYVZu_x&index=11']

jokes = """
What's the best thing about Switzerland? I don't know, but their flag is a huge plus.:Never criticize someone until you have walked a mile in their shoes. That way, when you criticize them, you'll be a mile away, and you'll have their shoes.:Two men meet on opposite sides of a river.  One shouts to the other, "I need you to help me get to the other side!" The other guy replies, "You're on the other side!":What do Alexander the Great and Winnie the Pooh have in common? Same middle name.:What do you call a shoe made out of a banana? A slipper.:They all laughed when I said I wanted to be a comedian. Well, they're not laughing now!

"""